version: '3'
services:
  try-rails7:
    container_name: try-rails7
    build:
      context: .
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=8080
    working_dir: /usr/src/app
  yaichi:
    image: mtsmfm/yaichi:1.7.0
    ports:
      - 80:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
